import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-sales-commission-incentive-compensation-audit",
  "engine": "recovery",
  "title": "Sales Commission & Incentive Compensation Audit",
  "shortTitle": "Commission Assurance",
  "tagline": "Reconcile bookings, crediting, attainment, accelerators, bonuses, clawbacks, and payroll",
  "industry": "Sales Compensation Operations",
  "uiPort": 4582,
  "apiPort": 5582,
  "accent": "#9333ea",
  "currency": "USD",
  "primaryOutcome": "Sales compensation calculated accurately, disputed efficiently, and reconciled to payroll and plan economics",
  "valueNarrative": "Connect compensation plans, employee assignments, quotas, CRM opportunities, bookings, invoices, cancellations, statements, and payroll.",
  "calculation": {
    "actualKey": "paidCompensation",
    "expectedKey": "earnedCompensation",
    "actualLabel": "Paid Compensation",
    "expectedLabel": "Calculated Earned Compensation",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Plan, assignment, booking, crediting, and attainment evidence indicate unpaid incentive compensation.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("compensation-plan-versioning","CA01","Compensation plan versioning","Reconcile compensation plan versioning using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed compensation plan versioning decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Compensation plan versioning Reference","text","CA01-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("employee-and-territory-registry","CA02","Employee and territory registry","Reconcile employee and territory registry using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed employee and territory registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Employee and territory registry Reference","text","CA02-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("quota-and-target-management","CA03","Quota and target management","Reconcile quota and target management using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed quota and target management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Quota and target management Reference","text","CA03-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("crm-opportunity-ingestion","CA04","CRM opportunity ingestion","Reconcile crm opportunity ingestion using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed crm opportunity ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","CRM opportunity ingestion Reference","text","CA04-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("booking-and-invoice-reconciliation","CA05","Booking and invoice reconciliation","Reconcile booking and invoice reconciliation using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed booking and invoice reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Booking and invoice reconciliation Reference","text","CA05-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("crediting-rule-application","CA06","Crediting-rule application","Reconcile crediting-rule application using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed crediting-rule application decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Crediting-rule application Reference","text","CA06-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("split-and-overlay-calculation","CA07","Split and overlay calculation","Reconcile split and overlay calculation using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed split and overlay calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Split and overlay calculation Reference","text","CA07-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("accelerator-calculation","CA08","Accelerator calculation","Reconcile accelerator calculation using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed accelerator calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Accelerator calculation Reference","text","CA08-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("product-and-strategic-bonus","CA09","Product and strategic bonus","Reconcile product and strategic bonus using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed product and strategic bonus decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Product and strategic bonus Reference","text","CA09-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("cancellation-and-clawback-validation","CA10","Cancellation and clawback validation","Reconcile cancellation and clawback validation using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed cancellation and clawback validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Cancellation and clawback validation Reference","text","CA10-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("draw-and-guarantee-tracking","CA11","Draw and guarantee tracking","Reconcile draw and guarantee tracking using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed draw and guarantee tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Draw and guarantee tracking Reference","text","CA11-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("statement-generation","CA12","Statement generation","Reconcile statement generation using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed statement generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Statement generation Reference","text","CA12-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("representative-dispute-workflow","CA13","Representative dispute workflow","Reconcile representative dispute workflow using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed representative dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Representative dispute workflow Reference","text","CA13-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("payroll-reconciliation","CA14","Payroll reconciliation","Reconcile payroll reconciliation using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed payroll reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Payroll reconciliation Reference","text","CA14-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("underpayment-recovery","CA15","Underpayment recovery","Reconcile underpayment recovery using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed underpayment recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Underpayment recovery Reference","text","CA15-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]}),
feature("plan-cost-and-behavior-analytics","CA16","Plan cost and behavior analytics","Reconcile plan cost and behavior analytics using compensation plans, employee and territory assignments, quotas, CRM opportunities, bookings, invoices, splits, cancellations, statements, and payroll.","Produce a governed plan cost and behavior analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["employeePlan","Employee / Plan","text","Jordan Lee / Enterprise FY26"],["caseReference","Plan cost and behavior analytics Reference","text","CA16-2026-001"],["paidCompensation","Paid Compensation","currency",184000],["earnedCompensation","Calculated Earned Compensation","currency",228500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidCompensation",subjects:["Enterprise account executive","Channel sales manager","Sales development team","Overlay specialist","Renewal representative"]})
]);
